### ISSUE TITLE
option to exclude file path and name from figure

### ISSUE THREAD

**Issue by jpesicek** [Jose-Alvarez/FMC#2]
feature request: 
more my use, the file name has to be manually cropped out later from the printed images.  It would be nice to have an option to add or remove this instead

**Comment by Jose-Alvarez** [comment]
Thanks for the suggestion. It should be easy to implement.

The idea could be an option like "-pt <optional title>". If -pt is present but no optional title is given then the file name is used as is done now, if -pt is not present then no title is added.

**Comment by Jose-Alvarez** [comment]
Ok, I have included now the option to customize the title. If nothing is set or -pt is used but without a string, then we use the plot file name as has been done in the previous versions. The string after -pt is used as custom title:

`FMC.py my_data.inp -p "my data.png" -pt "A quite long title, although not very, very long"`

![my data](https://user-images.githubusercontent.com/34281458/57857068-a07d5180-77ee-11e9-9c0e-b992fef70a6d.png)

To clear the title just use `-pt " "`

` FMC.py my_data.inp -p "my data no title.png" -pt " "`

![my data no title](https://user-images.githubusercontent.com/34281458/57857194-e803dd80-77ee-11e9-96e9-61285b0dcaf8.png)
