### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jpesicek** [Jose-Alvarez/FMC#3]
Hi, I recently upgraded to the new master branch, and I upgraded all my relevant software packages and now I get an error when doing a basic plotting example:

### this first example using standard in works fine:
$ echo -2.54 37.09 12 -3.4669 -2.0652 5.5321 6.2368 -1.8004 -5.1775 22 X Y ID | FMC.py -p  "My data.png"
#Longitude Latitude Depth_(km) mrr mtt mff mrt mrf mtf Exponent_(dyn-cm) X_position(GMT) Y_position(GMT) ID Rupture_type
-2.54 37.09 12.0 -3.4669 -2.0652 5.5321 6.2368 -1.8004 -5.1775 22.0 X Y ID N-SS

### # this second example using the same event, but in an input file, fails:
$ echo -2.54 37.09 12 -3.4669 -2.0652 5.5321 6.2368 -1.8004 -5.1775 22 X Y ID > my_data.inp

$ FMC.py -p "my_data_test.png" my_data.inp
Traceback (most recent call last):
  File "./FMC.py", line 203, in <module>
    data = genfromtxt(args.infile, dtype=None, encoding='str')
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/lib/npyio.py", line 1744, in genfromtxt
    fhd = iter(np.lib._datasource.open(fname, 'rt', encoding=encoding))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 266, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/numpy/lib/_datasource.py", line 622, in open
    encoding=encoding, newline=newline)
LookupError: unknown encoding: str

### #this must be some sort of version issue, but my versions are all up to date.

thanks,
Jeremy

**Comment by Jose-Alvarez** [comment]
Confirmed. It also happens on my system using python3. Using python 2.7.X it works fine.

**Comment by Jose-Alvarez** [comment]
It works using in FMC.py:
data = genfromtxt(args.infile, dtype=None, encoding=None)
"encoding=None" defines the data encoding to the system default.

Updated in master branch.
